// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ddm.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pb {

  /// <summary>Holder for reflection information generated from ddm.proto</summary>
  public static partial class DdmReflection {

    #region Descriptor
    /// <summary>File descriptor for ddm.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DdmReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CglkZG0ucHJvdG8SAnBiItsDCgdERE1EYXRhEhQKDG1hY2hpbmVfdGltZRgB",
            "IAIoARIQCghzaW1fdGltZRgCIAIoARIkCghzaW1fdmFycxgDIAMoCzISLnBi",
            "LkRETURhdGEuU2ltVmFyEhQKDGlzX3N0YXJ0X3NpbRgEIAEoCBITCgtpc19z",
            "dG9wX3NpbRgFIAEoCBIiCgd0bV92YXJzGAYgAygLMhEucGIuRERNRGF0YS5U",
            "bVZhchIiCgdmY192YXJzGAcgAygLMhEucGIuRERNRGF0YS5GY1ZhchrDAQoG",
            "U2ltVmFyEgwKBG5hbWUYASACKAkSJQoEdHlwZRgCIAIoDjIXLnBiLkRETURh",
            "dGEuU2ltVmFyLlR5cGUSFAoMZG91YmxlX3ZhbHVlGAMgASgBEhEKCWludF92",
            "YWx1ZRgEIAEoARISCgpib29sX3ZhbHVlGAUgASgBEhQKDHN0cmluZ192YWx1",
            "ZRgGIAEoCSIxCgRUeXBlEggKBEJvb2wQARIHCgNJbnQQAhIKCgZEb3VibGUQ",
            "AxIKCgZTdHJpbmcQBBokCgVUbVZhchIMCgRjb2RlGAEgAigJEg0KBXZhbHVl",
            "GAIgAigBGiMKBUZjVmFyEgwKBGNvZGUYASACKAkSDAoEdGltZRgCIAIoAQ=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.DDMData), global::Pb.DDMData.Parser, new[]{ "MachineTime", "SimTime", "SimVars", "IsStartSim", "IsStopSim", "TmVars", "FcVars" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Pb.DDMData.Types.SimVar), global::Pb.DDMData.Types.SimVar.Parser, new[]{ "Name", "Type", "DoubleValue", "IntValue", "BoolValue", "StringValue" }, null, new[]{ typeof(global::Pb.DDMData.Types.SimVar.Types.Type) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.DDMData.Types.TmVar), global::Pb.DDMData.Types.TmVar.Parser, new[]{ "Code", "Value" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.DDMData.Types.FcVar), global::Pb.DDMData.Types.FcVar.Parser, new[]{ "Code", "Time" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class DDMData : pb::IMessage<DDMData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DDMData> _parser = new pb::MessageParser<DDMData>(() => new DDMData());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DDMData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.DdmReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DDMData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DDMData(DDMData other) : this() {
      _hasBits0 = other._hasBits0;
      machineTime_ = other.machineTime_;
      simTime_ = other.simTime_;
      simVars_ = other.simVars_.Clone();
      isStartSim_ = other.isStartSim_;
      isStopSim_ = other.isStopSim_;
      tmVars_ = other.tmVars_.Clone();
      fcVars_ = other.fcVars_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DDMData Clone() {
      return new DDMData(this);
    }

    /// <summary>Field number for the "machine_time" field.</summary>
    public const int MachineTimeFieldNumber = 1;
    private readonly static double MachineTimeDefaultValue = 0D;

    private double machineTime_;
    /// <summary>
    ///机器时，基准1970-01-01 00：00：00（必须）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double MachineTime {
      get { if ((_hasBits0 & 1) != 0) { return machineTime_; } else { return MachineTimeDefaultValue; } }
      set {
        _hasBits0 |= 1;
        machineTime_ = value;
      }
    }
    /// <summary>Gets whether the "machine_time" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMachineTime {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "machine_time" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMachineTime() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "sim_time" field.</summary>
    public const int SimTimeFieldNumber = 2;
    private readonly static double SimTimeDefaultValue = 0D;

    private double simTime_;
    /// <summary>
    ///仿真时间（必须）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double SimTime {
      get { if ((_hasBits0 & 2) != 0) { return simTime_; } else { return SimTimeDefaultValue; } }
      set {
        _hasBits0 |= 2;
        simTime_ = value;
      }
    }
    /// <summary>Gets whether the "sim_time" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSimTime {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "sim_time" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSimTime() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "sim_vars" field.</summary>
    public const int SimVarsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Pb.DDMData.Types.SimVar> _repeated_simVars_codec
        = pb::FieldCodec.ForMessage(26, global::Pb.DDMData.Types.SimVar.Parser);
    private readonly pbc::RepeatedField<global::Pb.DDMData.Types.SimVar> simVars_ = new pbc::RepeatedField<global::Pb.DDMData.Types.SimVar>();
    /// <summary>
    ///仿真变量数组
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Pb.DDMData.Types.SimVar> SimVars {
      get { return simVars_; }
    }

    /// <summary>Field number for the "is_start_sim" field.</summary>
    public const int IsStartSimFieldNumber = 4;
    private readonly static bool IsStartSimDefaultValue = false;

    private bool isStartSim_;
    /// <summary>
    ///仿真开始
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsStartSim {
      get { if ((_hasBits0 & 4) != 0) { return isStartSim_; } else { return IsStartSimDefaultValue; } }
      set {
        _hasBits0 |= 4;
        isStartSim_ = value;
      }
    }
    /// <summary>Gets whether the "is_start_sim" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasIsStartSim {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "is_start_sim" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearIsStartSim() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "is_stop_sim" field.</summary>
    public const int IsStopSimFieldNumber = 5;
    private readonly static bool IsStopSimDefaultValue = false;

    private bool isStopSim_;
    /// <summary>
    ///仿真停止
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsStopSim {
      get { if ((_hasBits0 & 8) != 0) { return isStopSim_; } else { return IsStopSimDefaultValue; } }
      set {
        _hasBits0 |= 8;
        isStopSim_ = value;
      }
    }
    /// <summary>Gets whether the "is_stop_sim" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasIsStopSim {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "is_stop_sim" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearIsStopSim() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "tm_vars" field.</summary>
    public const int TmVarsFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Pb.DDMData.Types.TmVar> _repeated_tmVars_codec
        = pb::FieldCodec.ForMessage(50, global::Pb.DDMData.Types.TmVar.Parser);
    private readonly pbc::RepeatedField<global::Pb.DDMData.Types.TmVar> tmVars_ = new pbc::RepeatedField<global::Pb.DDMData.Types.TmVar>();
    /// <summary>
    ///遥测数组
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Pb.DDMData.Types.TmVar> TmVars {
      get { return tmVars_; }
    }

    /// <summary>Field number for the "fc_vars" field.</summary>
    public const int FcVarsFieldNumber = 7;
    private static readonly pb::FieldCodec<global::Pb.DDMData.Types.FcVar> _repeated_fcVars_codec
        = pb::FieldCodec.ForMessage(58, global::Pb.DDMData.Types.FcVar.Parser);
    private readonly pbc::RepeatedField<global::Pb.DDMData.Types.FcVar> fcVars_ = new pbc::RepeatedField<global::Pb.DDMData.Types.FcVar>();
    /// <summary>
    ///飞控指令数组
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Pb.DDMData.Types.FcVar> FcVars {
      get { return fcVars_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DDMData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DDMData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(MachineTime, other.MachineTime)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(SimTime, other.SimTime)) return false;
      if(!simVars_.Equals(other.simVars_)) return false;
      if (IsStartSim != other.IsStartSim) return false;
      if (IsStopSim != other.IsStopSim) return false;
      if(!tmVars_.Equals(other.tmVars_)) return false;
      if(!fcVars_.Equals(other.fcVars_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasMachineTime) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(MachineTime);
      if (HasSimTime) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(SimTime);
      hash ^= simVars_.GetHashCode();
      if (HasIsStartSim) hash ^= IsStartSim.GetHashCode();
      if (HasIsStopSim) hash ^= IsStopSim.GetHashCode();
      hash ^= tmVars_.GetHashCode();
      hash ^= fcVars_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasMachineTime) {
        output.WriteRawTag(9);
        output.WriteDouble(MachineTime);
      }
      if (HasSimTime) {
        output.WriteRawTag(17);
        output.WriteDouble(SimTime);
      }
      simVars_.WriteTo(output, _repeated_simVars_codec);
      if (HasIsStartSim) {
        output.WriteRawTag(32);
        output.WriteBool(IsStartSim);
      }
      if (HasIsStopSim) {
        output.WriteRawTag(40);
        output.WriteBool(IsStopSim);
      }
      tmVars_.WriteTo(output, _repeated_tmVars_codec);
      fcVars_.WriteTo(output, _repeated_fcVars_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasMachineTime) {
        output.WriteRawTag(9);
        output.WriteDouble(MachineTime);
      }
      if (HasSimTime) {
        output.WriteRawTag(17);
        output.WriteDouble(SimTime);
      }
      simVars_.WriteTo(ref output, _repeated_simVars_codec);
      if (HasIsStartSim) {
        output.WriteRawTag(32);
        output.WriteBool(IsStartSim);
      }
      if (HasIsStopSim) {
        output.WriteRawTag(40);
        output.WriteBool(IsStopSim);
      }
      tmVars_.WriteTo(ref output, _repeated_tmVars_codec);
      fcVars_.WriteTo(ref output, _repeated_fcVars_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasMachineTime) {
        size += 1 + 8;
      }
      if (HasSimTime) {
        size += 1 + 8;
      }
      size += simVars_.CalculateSize(_repeated_simVars_codec);
      if (HasIsStartSim) {
        size += 1 + 1;
      }
      if (HasIsStopSim) {
        size += 1 + 1;
      }
      size += tmVars_.CalculateSize(_repeated_tmVars_codec);
      size += fcVars_.CalculateSize(_repeated_fcVars_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DDMData other) {
      if (other == null) {
        return;
      }
      if (other.HasMachineTime) {
        MachineTime = other.MachineTime;
      }
      if (other.HasSimTime) {
        SimTime = other.SimTime;
      }
      simVars_.Add(other.simVars_);
      if (other.HasIsStartSim) {
        IsStartSim = other.IsStartSim;
      }
      if (other.HasIsStopSim) {
        IsStopSim = other.IsStopSim;
      }
      tmVars_.Add(other.tmVars_);
      fcVars_.Add(other.fcVars_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            MachineTime = input.ReadDouble();
            break;
          }
          case 17: {
            SimTime = input.ReadDouble();
            break;
          }
          case 26: {
            simVars_.AddEntriesFrom(input, _repeated_simVars_codec);
            break;
          }
          case 32: {
            IsStartSim = input.ReadBool();
            break;
          }
          case 40: {
            IsStopSim = input.ReadBool();
            break;
          }
          case 50: {
            tmVars_.AddEntriesFrom(input, _repeated_tmVars_codec);
            break;
          }
          case 58: {
            fcVars_.AddEntriesFrom(input, _repeated_fcVars_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            MachineTime = input.ReadDouble();
            break;
          }
          case 17: {
            SimTime = input.ReadDouble();
            break;
          }
          case 26: {
            simVars_.AddEntriesFrom(ref input, _repeated_simVars_codec);
            break;
          }
          case 32: {
            IsStartSim = input.ReadBool();
            break;
          }
          case 40: {
            IsStopSim = input.ReadBool();
            break;
          }
          case 50: {
            tmVars_.AddEntriesFrom(ref input, _repeated_tmVars_codec);
            break;
          }
          case 58: {
            fcVars_.AddEntriesFrom(ref input, _repeated_fcVars_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the DDMData message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      ///单个仿真变量数据类型
      /// </summary>
      public sealed partial class SimVar : pb::IMessage<SimVar>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<SimVar> _parser = new pb::MessageParser<SimVar>(() => new SimVar());
        private pb::UnknownFieldSet _unknownFields;
        private int _hasBits0;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<SimVar> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Pb.DDMData.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SimVar() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SimVar(SimVar other) : this() {
          _hasBits0 = other._hasBits0;
          name_ = other.name_;
          type_ = other.type_;
          doubleValue_ = other.doubleValue_;
          intValue_ = other.intValue_;
          boolValue_ = other.boolValue_;
          stringValue_ = other.stringValue_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SimVar Clone() {
          return new SimVar(this);
        }

        /// <summary>Field number for the "name" field.</summary>
        public const int NameFieldNumber = 1;
        private readonly static string NameDefaultValue = "";

        private string name_;
        /// <summary>
        ///变量全名（必须）
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Name {
          get { return name_ ?? NameDefaultValue; }
          set {
            name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }
        /// <summary>Gets whether the "name" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasName {
          get { return name_ != null; }
        }
        /// <summary>Clears the value of the "name" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearName() {
          name_ = null;
        }

        /// <summary>Field number for the "type" field.</summary>
        public const int TypeFieldNumber = 2;
        private readonly static global::Pb.DDMData.Types.SimVar.Types.Type TypeDefaultValue = global::Pb.DDMData.Types.SimVar.Types.Type.Bool;

        private global::Pb.DDMData.Types.SimVar.Types.Type type_;
        /// <summary>
        ///变量类型：Bool/Int/Double（必须）
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Pb.DDMData.Types.SimVar.Types.Type Type {
          get { if ((_hasBits0 & 1) != 0) { return type_; } else { return TypeDefaultValue; } }
          set {
            _hasBits0 |= 1;
            type_ = value;
          }
        }
        /// <summary>Gets whether the "type" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasType {
          get { return (_hasBits0 & 1) != 0; }
        }
        /// <summary>Clears the value of the "type" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearType() {
          _hasBits0 &= ~1;
        }

        /// <summary>Field number for the "double_value" field.</summary>
        public const int DoubleValueFieldNumber = 3;
        private readonly static double DoubleValueDefaultValue = 0D;

        private double doubleValue_;
        /// <summary>
        ///double类型值（可选）
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double DoubleValue {
          get { if ((_hasBits0 & 2) != 0) { return doubleValue_; } else { return DoubleValueDefaultValue; } }
          set {
            _hasBits0 |= 2;
            doubleValue_ = value;
          }
        }
        /// <summary>Gets whether the "double_value" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasDoubleValue {
          get { return (_hasBits0 & 2) != 0; }
        }
        /// <summary>Clears the value of the "double_value" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearDoubleValue() {
          _hasBits0 &= ~2;
        }

        /// <summary>Field number for the "int_value" field.</summary>
        public const int IntValueFieldNumber = 4;
        private readonly static double IntValueDefaultValue = 0D;

        private double intValue_;
        /// <summary>
        ///int类型值（可选）
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double IntValue {
          get { if ((_hasBits0 & 4) != 0) { return intValue_; } else { return IntValueDefaultValue; } }
          set {
            _hasBits0 |= 4;
            intValue_ = value;
          }
        }
        /// <summary>Gets whether the "int_value" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasIntValue {
          get { return (_hasBits0 & 4) != 0; }
        }
        /// <summary>Clears the value of the "int_value" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearIntValue() {
          _hasBits0 &= ~4;
        }

        /// <summary>Field number for the "bool_value" field.</summary>
        public const int BoolValueFieldNumber = 5;
        private readonly static double BoolValueDefaultValue = 0D;

        private double boolValue_;
        /// <summary>
        ///bool类型值（可选）
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double BoolValue {
          get { if ((_hasBits0 & 8) != 0) { return boolValue_; } else { return BoolValueDefaultValue; } }
          set {
            _hasBits0 |= 8;
            boolValue_ = value;
          }
        }
        /// <summary>Gets whether the "bool_value" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasBoolValue {
          get { return (_hasBits0 & 8) != 0; }
        }
        /// <summary>Clears the value of the "bool_value" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearBoolValue() {
          _hasBits0 &= ~8;
        }

        /// <summary>Field number for the "string_value" field.</summary>
        public const int StringValueFieldNumber = 6;
        private readonly static string StringValueDefaultValue = "";

        private string stringValue_;
        /// <summary>
        ///string类型值（可选）
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string StringValue {
          get { return stringValue_ ?? StringValueDefaultValue; }
          set {
            stringValue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }
        /// <summary>Gets whether the "string_value" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasStringValue {
          get { return stringValue_ != null; }
        }
        /// <summary>Clears the value of the "string_value" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearStringValue() {
          stringValue_ = null;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as SimVar);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(SimVar other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Name != other.Name) return false;
          if (Type != other.Type) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(DoubleValue, other.DoubleValue)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(IntValue, other.IntValue)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(BoolValue, other.BoolValue)) return false;
          if (StringValue != other.StringValue) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (HasName) hash ^= Name.GetHashCode();
          if (HasType) hash ^= Type.GetHashCode();
          if (HasDoubleValue) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(DoubleValue);
          if (HasIntValue) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(IntValue);
          if (HasBoolValue) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(BoolValue);
          if (HasStringValue) hash ^= StringValue.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (HasName) {
            output.WriteRawTag(10);
            output.WriteString(Name);
          }
          if (HasType) {
            output.WriteRawTag(16);
            output.WriteEnum((int) Type);
          }
          if (HasDoubleValue) {
            output.WriteRawTag(25);
            output.WriteDouble(DoubleValue);
          }
          if (HasIntValue) {
            output.WriteRawTag(33);
            output.WriteDouble(IntValue);
          }
          if (HasBoolValue) {
            output.WriteRawTag(41);
            output.WriteDouble(BoolValue);
          }
          if (HasStringValue) {
            output.WriteRawTag(50);
            output.WriteString(StringValue);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (HasName) {
            output.WriteRawTag(10);
            output.WriteString(Name);
          }
          if (HasType) {
            output.WriteRawTag(16);
            output.WriteEnum((int) Type);
          }
          if (HasDoubleValue) {
            output.WriteRawTag(25);
            output.WriteDouble(DoubleValue);
          }
          if (HasIntValue) {
            output.WriteRawTag(33);
            output.WriteDouble(IntValue);
          }
          if (HasBoolValue) {
            output.WriteRawTag(41);
            output.WriteDouble(BoolValue);
          }
          if (HasStringValue) {
            output.WriteRawTag(50);
            output.WriteString(StringValue);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (HasName) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
          }
          if (HasType) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
          }
          if (HasDoubleValue) {
            size += 1 + 8;
          }
          if (HasIntValue) {
            size += 1 + 8;
          }
          if (HasBoolValue) {
            size += 1 + 8;
          }
          if (HasStringValue) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(StringValue);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(SimVar other) {
          if (other == null) {
            return;
          }
          if (other.HasName) {
            Name = other.Name;
          }
          if (other.HasType) {
            Type = other.Type;
          }
          if (other.HasDoubleValue) {
            DoubleValue = other.DoubleValue;
          }
          if (other.HasIntValue) {
            IntValue = other.IntValue;
          }
          if (other.HasBoolValue) {
            BoolValue = other.BoolValue;
          }
          if (other.HasStringValue) {
            StringValue = other.StringValue;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Name = input.ReadString();
                break;
              }
              case 16: {
                Type = (global::Pb.DDMData.Types.SimVar.Types.Type) input.ReadEnum();
                break;
              }
              case 25: {
                DoubleValue = input.ReadDouble();
                break;
              }
              case 33: {
                IntValue = input.ReadDouble();
                break;
              }
              case 41: {
                BoolValue = input.ReadDouble();
                break;
              }
              case 50: {
                StringValue = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                Name = input.ReadString();
                break;
              }
              case 16: {
                Type = (global::Pb.DDMData.Types.SimVar.Types.Type) input.ReadEnum();
                break;
              }
              case 25: {
                DoubleValue = input.ReadDouble();
                break;
              }
              case 33: {
                IntValue = input.ReadDouble();
                break;
              }
              case 41: {
                BoolValue = input.ReadDouble();
                break;
              }
              case 50: {
                StringValue = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

        #region Nested types
        /// <summary>Container for nested types declared in the SimVar message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types {
          /// <summary>
          ///变量值类型
          /// </summary>
          public enum Type {
            [pbr::OriginalName("Bool")] Bool = 1,
            [pbr::OriginalName("Int")] Int = 2,
            [pbr::OriginalName("Double")] Double = 3,
            [pbr::OriginalName("String")] String = 4,
          }

        }
        #endregion

      }

      public sealed partial class TmVar : pb::IMessage<TmVar>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<TmVar> _parser = new pb::MessageParser<TmVar>(() => new TmVar());
        private pb::UnknownFieldSet _unknownFields;
        private int _hasBits0;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<TmVar> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Pb.DDMData.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public TmVar() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public TmVar(TmVar other) : this() {
          _hasBits0 = other._hasBits0;
          code_ = other.code_;
          value_ = other.value_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public TmVar Clone() {
          return new TmVar(this);
        }

        /// <summary>Field number for the "code" field.</summary>
        public const int CodeFieldNumber = 1;
        private readonly static string CodeDefaultValue = "";

        private string code_;
        /// <summary>
        ///遥测代号（必须）
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Code {
          get { return code_ ?? CodeDefaultValue; }
          set {
            code_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }
        /// <summary>Gets whether the "code" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasCode {
          get { return code_ != null; }
        }
        /// <summary>Clears the value of the "code" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearCode() {
          code_ = null;
        }

        /// <summary>Field number for the "value" field.</summary>
        public const int ValueFieldNumber = 2;
        private readonly static double ValueDefaultValue = 0D;

        private double value_;
        /// <summary>
        ///遥测值（必须）
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double Value {
          get { if ((_hasBits0 & 1) != 0) { return value_; } else { return ValueDefaultValue; } }
          set {
            _hasBits0 |= 1;
            value_ = value;
          }
        }
        /// <summary>Gets whether the "value" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasValue {
          get { return (_hasBits0 & 1) != 0; }
        }
        /// <summary>Clears the value of the "value" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearValue() {
          _hasBits0 &= ~1;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as TmVar);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(TmVar other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Code != other.Code) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Value, other.Value)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (HasCode) hash ^= Code.GetHashCode();
          if (HasValue) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Value);
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (HasCode) {
            output.WriteRawTag(10);
            output.WriteString(Code);
          }
          if (HasValue) {
            output.WriteRawTag(17);
            output.WriteDouble(Value);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (HasCode) {
            output.WriteRawTag(10);
            output.WriteString(Code);
          }
          if (HasValue) {
            output.WriteRawTag(17);
            output.WriteDouble(Value);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (HasCode) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Code);
          }
          if (HasValue) {
            size += 1 + 8;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(TmVar other) {
          if (other == null) {
            return;
          }
          if (other.HasCode) {
            Code = other.Code;
          }
          if (other.HasValue) {
            Value = other.Value;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Code = input.ReadString();
                break;
              }
              case 17: {
                Value = input.ReadDouble();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                Code = input.ReadString();
                break;
              }
              case 17: {
                Value = input.ReadDouble();
                break;
              }
            }
          }
        }
        #endif

      }

      public sealed partial class FcVar : pb::IMessage<FcVar>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<FcVar> _parser = new pb::MessageParser<FcVar>(() => new FcVar());
        private pb::UnknownFieldSet _unknownFields;
        private int _hasBits0;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<FcVar> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Pb.DDMData.Descriptor.NestedTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public FcVar() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public FcVar(FcVar other) : this() {
          _hasBits0 = other._hasBits0;
          code_ = other.code_;
          time_ = other.time_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public FcVar Clone() {
          return new FcVar(this);
        }

        /// <summary>Field number for the "code" field.</summary>
        public const int CodeFieldNumber = 1;
        private readonly static string CodeDefaultValue = "";

        private string code_;
        /// <summary>
        ///飞控指令代号（必须）
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Code {
          get { return code_ ?? CodeDefaultValue; }
          set {
            code_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }
        /// <summary>Gets whether the "code" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasCode {
          get { return code_ != null; }
        }
        /// <summary>Clears the value of the "code" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearCode() {
          code_ = null;
        }

        /// <summary>Field number for the "time" field.</summary>
        public const int TimeFieldNumber = 2;
        private readonly static double TimeDefaultValue = 0D;

        private double time_;
        /// <summary>
        ///时间，基准1970-01-01 00：00：00（必须）
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public double Time {
          get { if ((_hasBits0 & 1) != 0) { return time_; } else { return TimeDefaultValue; } }
          set {
            _hasBits0 |= 1;
            time_ = value;
          }
        }
        /// <summary>Gets whether the "time" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasTime {
          get { return (_hasBits0 & 1) != 0; }
        }
        /// <summary>Clears the value of the "time" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearTime() {
          _hasBits0 &= ~1;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as FcVar);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(FcVar other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Code != other.Code) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Time, other.Time)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (HasCode) hash ^= Code.GetHashCode();
          if (HasTime) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Time);
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (HasCode) {
            output.WriteRawTag(10);
            output.WriteString(Code);
          }
          if (HasTime) {
            output.WriteRawTag(17);
            output.WriteDouble(Time);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (HasCode) {
            output.WriteRawTag(10);
            output.WriteString(Code);
          }
          if (HasTime) {
            output.WriteRawTag(17);
            output.WriteDouble(Time);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (HasCode) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Code);
          }
          if (HasTime) {
            size += 1 + 8;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(FcVar other) {
          if (other == null) {
            return;
          }
          if (other.HasCode) {
            Code = other.Code;
          }
          if (other.HasTime) {
            Time = other.Time;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Code = input.ReadString();
                break;
              }
              case 17: {
                Time = input.ReadDouble();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                Code = input.ReadString();
                break;
              }
              case 17: {
                Time = input.ReadDouble();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
